apiVersion: v1
kind: Service
metadata:
  name: service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: prueba
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 4200 #Service port
    targetPort: 4200